[workspace]
resolver = "2"
members = [
    "components/internal-client",
    "crates/test-harness",
]

[workspace.dependencies]
chrono = { git = "https://github.com/chronotope/chrono.git", branch = "0.5.x" }
httpdate = "1.0"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.11"
test-harness = { path = "./crates/test-harness" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
url = "2.5"
wasmtime = { version = "49", features = ["component-model-async"] }
wasmtime-wasi = { version = "49", features = ["p3"] }
wit-bindgen = "0.62.0"
