[package]
name = "client"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { workspace = true }
httpdate = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
url = { workspace = true }
wit-bindgen = { workspace = true, features = ["async-spawn"] }

[dev-dependencies]
test-harness = { workspace = true }
tokio = { workspace = true }
wasmtime = { workspace = true }
